config/routes.rb
TatTrack::Application.routes.draw do
  resources :tat_trackers

end

app/models/tat_tracker.rb
class TatTracker < ActiveRecord::Base
  attr_accessible :artist_email, :artist_location, :artist_name, :artist_phone, :artist_twitter, :date_inked, :inspiration, :location_on_body, :picture, :username
  mount_uploader :picture, PictureUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/tat_trackers_controller.rb
class TatTrackersController < ApplicationController
  # GET /tat_trackers
  # GET /tat_trackers.json
  def index
    @tat_trackers = TatTracker.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tat_trackers }
    end
  end

  # GET /tat_trackers/1
  # GET /tat_trackers/1.json
  def show
    @tat_tracker = TatTracker.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tat_tracker }
    end
  end

  # GET /tat_trackers/new
  # GET /tat_trackers/new.json
  def new
    @tat_tracker = TatTracker.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tat_tracker }
    end
  end

  # GET /tat_trackers/1/edit
  def edit
    @tat_tracker = TatTracker.find(params[:id])
  end

  # POST /tat_trackers
  # POST /tat_trackers.json
  def create
    @tat_tracker = TatTracker.new(params[:tat_tracker])

    respond_to do |format|
      if @tat_tracker.save
        format.html { redirect_to @tat_tracker, notice: 'Tat tracker was successfully created.' }
        format.json { render json: @tat_tracker, status: :created, location: @tat_tracker }
      else
        format.html { render action: "new" }
        format.json { render json: @tat_tracker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tat_trackers/1
  # PUT /tat_trackers/1.json
  def update
    @tat_tracker = TatTracker.find(params[:id])

    respond_to do |format|
      if @tat_tracker.update_attributes(params[:tat_tracker])
        format.html { redirect_to @tat_tracker, notice: 'Tat tracker was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tat_tracker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tat_trackers/1
  # DELETE /tat_trackers/1.json
  def destroy
    @tat_tracker = TatTracker.find(params[:id])
    @tat_tracker.destroy

    respond_to do |format|
      format.html { redirect_to tat_trackers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tat_trackers_helper.rb
module TatTrackersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TatTrack</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tat_trackers/_form.html.erb
<%= form_for(@tat_tracker, :html => {:multipart => true}) do |f| %>
  <% if @tat_tracker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tat_tracker.errors.count, "error") %> prohibited this tat_tracker from being saved:</h2>

      <ul>
      <% @tat_tracker.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :picture %><br />
    <%= f.file_field :picture %>
  </div>
  <div class="field">
    <%= f.label :date_inked %><br />
    <%= f.date_select :date_inked %>
  </div>
  <div class="field">
    <%= f.label :inspiration %><br />
    <%= f.text_area :inspiration %>
  </div>
  <div class="field">
    <%= f.label :location_on_body %><br />
    <%= f.text_field :location_on_body %>
  </div>
  <div class="field">
    <%= f.label :artist_name %><br />
    <%= f.text_field :artist_name %>
  </div>
  <div class="field">
    <%= f.label :artist_location %><br />
    <%= f.text_field :artist_location %>
  </div>
  <div class="field">
    <%= f.label :artist_email %><br />
    <%= f.text_field :artist_email %>
  </div>
  <div class="field">
    <%= f.label :artist_twitter %><br />
    <%= f.text_field :artist_twitter %>
  </div>
  <div class="field">
    <%= f.label :artist_phone %><br />
    <%= f.text_field :artist_phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tat_trackers/edit.html.erb
<h1>Editing tat_tracker</h1>

<%= render 'form' %>

<%= link_to 'Show', @tat_tracker %> |
<%= link_to 'Back', tat_trackers_path %>

app/views/tat_trackers/index.html.haml
%h1 Add Your Tat

%table
  %tr
    %th Username
    %th Picture
    %th Date inked
    %th Inspiration
    %th Location on body
    %th Artist name
    %th Artist location
    %th Artist email
    %th Artist twitter
    %th Artist phone
    %th
    %th
    %th
  

  -@tat_trackers.each do |tat_tracker| 
    %tr
      %td= tat_tracker.username 
      %td= tat_tracker.picture 
      %td= tat_tracker.date_inked 
      %td= tat_tracker.inspiration 
      %td= tat_tracker.location_on_body 
      %td= tat_tracker.artist_name 
      %td= tat_tracker.artist_location 
      %td= tat_tracker.artist_email 
      %td= tat_tracker.artist_twitter 
      %td= tat_tracker.artist_phone 
      %td= link_to 'Show', tat_tracker 
      %td= link_to 'Edit', edit_tat_tracker_path(tat_tracker) 
      %td= link_to 'Delete', tat_tracker, method: :delete, data: { confirm: 'Are you sure? That shit is permanent' } 
 
= link_to 'Add A Tat', new_tat_tracker_path 

app/views/tat_trackers/new.html.erb
<h1>Your Tat</h1>

<%= render 'form' %>

<%= link_to 'Back', tat_trackers_path %>

app/views/tat_trackers/show.html.haml
%p#notice.flash-message=notice

%p
  %strong Username:
  = @tat_tracker.username 

%p
  %strong Picture:
  = image_tag(@tat_tracker.picture_url) if @tat_tracker.picture.present?

%p
  %strong Date inked:
  = @tat_tracker.date_inked 

%p
  %strong Inspiration:
  = @tat_tracker.inspiration 

%p
  %strong Location on body:
  = @tat_tracker.location_on_body 

%p
  %strong Artist name:
  = @tat_tracker.artist_name 

%p
  %strong Artist location:
  = @tat_tracker.artist_location 

%p
  %strong Artist email:
  = @tat_tracker.artist_email 

%p
  %strong Artist twitter:
  = @tat_tracker.artist_twitter 

%p
  %strong Artist phone:
  = @tat_tracker.artist_phone 

||
= link_to 'Edit', edit_tat_tracker_path(@tat_tracker)  
||
= link_to 'Back', tat_trackers_path
||
= link_to 'Delete', @tat_tracker, method: 'delete', data: { confirm: 'Are you sure? You cant delete a tat in real life.' } 
||